version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
    build: ./restapi
    ports:
      - "5000:5000"
  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./restapi/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - restapi