version: '3.5'
services:
  restapi:
    image: ghcr.io/Arquisoft/dede_es6c/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/Arquisoft/dede_es6c/webapp:latest
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-restapi,docker-push-webapp]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget https://raw.githubusercontent.com/Arquisoft/dede_es6c/master/docker-compose-deploy.yml -O docker-compose.yml
          docker-compose stop
          docker-compose rm -f
          docker-compose pull   
          docker-compose up -d
env:
   API_URI: http://${{ secrets.DEPLOY_HOST }}:5000/api